import React from 'react';
import Head from 'next/head';

const PrivacyPolicy = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy</title>
      </Head>
      <main className="container mx-auto p-4">
        <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
        <p className="mb-4">
          Your privacy is important to us. This privacy policy document outlines the types of personal information that is received and collected by our website and how it is used.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-2">Cookies and Google AdSense</h2>
        <p className="mb-4">
          Our website uses Google AdSense, a service for including advertisements from Google Inc. ("Google"). Google AdSense uses so-called "cookies", text files that are stored on your computer and that allow an analysis of the use of the website.
        </p>
        <p className="mb-4">
          Google AdSense also uses so-called "web beacons" (invisible graphics). These web beacons can be used to evaluate information such as visitor traffic on these pages.
        </p>
        <p className="mb-4">
          The information generated by the cookie and web beacon about the use of this website (including your IP address) and delivery of advertising formats are transmitted to and stored by Google on servers in the United States. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf.
        </p>
        <p className="mb-4">
          You can prevent the installation of cookies by setting your browser software accordingly; however, please be aware that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.
        </p>
        
        <h2 className="text-2xl font-semibold mt-6 mb-2">Google Analytics</h2>
        <p className="mb-4">
          We use Google Analytics to help us understand how visitors interact with our website. This service collects data such as your IP address, browser type, operating system, and the pages you visit. This information is used to compile reports and to help us improve the site. Google Analytics uses cookies to track user activity. The data collected is anonymous and does not personally identify you.
        </p>
        <p className="mb-4">
          You can opt-out of Google Analytics without affecting how you visit our site. For more information on how to opt-out of being tracked by Google Analytics across all websites you use, visit the Google Analytics Opt-out Browser Add-on page: <a href="https://tools.google.com/dlpage/gaoptout" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">https://tools.google.com/dlpage/gaoptout</a>.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-2">First-Party Cookies (Quiz Answers)</h2>
        <p className="mb-4">
          In addition to third-party cookies from services like Google AdSense and Google Analytics, our website uses "first-party" cookies to enhance your experience. Specifically, when you participate in a quiz on our site, we use a cookie to temporarily store your quiz answers for a period of up to 24 hours. This cookie is essential for the functionality of the quiz feature and allows us to remember your progress and show you your results. This data is not shared with any third parties and is automatically deleted after 24 hours.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-2">DoubleClick DART Cookie</h2>
        <p className="mb-4">
          Google, as a third-party vendor, uses cookies to serve ads on this site. Google's use of the DART cookie enables it to serve ads to users based on their visit to this site and other sites on the Internet.
        </p>
        <p className="mb-4">
          Users may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy at the following URL: <a href="https://policies.google.com/technologies/ads" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">https://policies.google.com/technologies/ads</a>.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-2">Log Files</h2>
        <p className="mb-4">
          Like many other websites, we make use of log files. The information inside the log files includes internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date/time stamp, referring/exit pages, and possibly the number of clicks. This information is used to analyze trends, administer the site, track user's movement around the site, and gather demographic information. IP addresses and other such information are not linked to any information that is personally identifiable.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-2">Consent</h2>
        <p className="mb-4">
          By using our website, you hereby consent to our privacy policy and agree to its terms.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-2">Update</h2>
        <p className="mb-4">
          This Privacy Policy was last updated on <strong>August 14, 2025</strong>. If we update, amend, or make any changes to our privacy policy, those changes will be posted here.
        </p>
      </main>
    </>
  );
};

export default PrivacyPolicy;
