import React from 'react';
import Head from 'next/head';

const PrivacyPolicy = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy</title>
      </Head>
      <main className="container mx-auto p-4">
        <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
        <p className="mb-4">
          Your privacy is important to us. This privacy policy document outlines the types of personal information that is received and collected by our website and how it is used.
        </p>
        
        <h2 className="text-2xl font-semibold mt-6 mb-2">Information We Collect</h2>
        <p className="mb-4">
          When you use our website, we may collect information in a few different ways.
        </p>

        <h3 className="text-xl font-semibold mt-4 mb-2">Contact Form</h3>
        <p className="mb-4">
          When you use the contact form at myhscounselor.com/contact, we collect the information you provide, including your first name, last name, and email address. We use this information solely to respond to your inquiries and communicate with you about your request. This data is not used for marketing purposes or shared with third parties without your explicit consent.
        </p>

        <h3 className="text-xl font-semibold mt-4 mb-2">Cookies and Third-Party Services</h3>
        <h4 className="text-lg font-semibold mt-2 mb-1">Google AdSense</h4>
        <p className="mb-4">
          Our website uses Google AdSense, a service for including advertisements from Google Inc. ("Google"). Google AdSense uses so-called "cookies", text files that are stored on your computer and that allow an analysis of the use of the website. The information generated by the cookie is transmitted to and stored by Google on servers in the United States. You can prevent the installation of cookies by setting your browser software accordingly.
        </p>
        
        <h4 className="text-lg font-semibold mt-2 mb-1">Google Analytics</h4>
        <p className="mb-4">
          We use Google Analytics to help us understand how visitors interact with our website. This service collects anonymous data such as your IP address, browser type, and the pages you visit. You can opt-out of Google Analytics by visiting the Google Analytics Opt-out Browser Add-on page: <a href="https://tools.google.com/dlpage/gaoptout" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">https://tools.google.com/dlpage/gaoptout</a>.
        </p>

        <h4 className="text-lg font-semibold mt-2 mb-1">First-Party Cookies (Quiz Answers)</h4>
        <p className="mb-4">
          Our website uses "first-party" cookies to enhance your experience. When you participate in a quiz, we use a cookie to temporarily store your quiz answers for up to 24 hours. This data is not shared with any third parties and is automatically deleted after 24 hours.
        </p>

        <h3 className="text-xl font-semibold mt-4 mb-2">Log Files</h3>
        <p className="mb-4">
          Like many other websites, we make use of log files. The information inside the log files includes internet protocol (IP) addresses, browser type, and other non-personally identifiable information. This information is used for website administration and to analyze trends.
        </p>
        
        <h2 className="text-2xl font-semibold mt-6 mb-2">Consent</h2>
        <p className="mb-4">
          By using our website, you hereby consent to our privacy policy and agree to its terms.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-2">Update</h2>
        <p className="mb-4">
          This Privacy Policy was last updated on <strong>August 14, 2025</strong>. If we update, amend, or make any changes to our privacy policy, those changes will be posted here.
        </p>
      </main>
    </>
  );
};

export default PrivacyPolicy;
